development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: postgres://kflgtsgohwxisu:92705dbadaf34bd845f429854e47f311a6dde35fadefc1c713d269607722f3fd@ec2-54-235-90-0.compute-1.amazonaws.com:5432/de1gkuqe7adgn1
